OfqualGovUK/experts-prototype

app/data/session-data-defaults.js
app/routes.js
app/views/_includes/summary-cards/experience.html
app/views/application/experience-details/conflict-of-interest.html
app/views/application/experience-details/index.html
app/views/application/experience-details/job-details.html
app/views/application/experience-details/review.html
app/views/application/experience-details/section-completed.html
app/views/application/experience-details/summary-of-activity.html
app/views/application/expertise/index.html
app/views/application/index.html

This PR moves the add employment section towards the start of the flow

Move employment history

---

app/views/_components/inset-text/template.html
app/views/application/index.html
app/views/application/review.html

This PR adds placeholder sections for the remained of the flow

Task list and review tidy up

---

app/config.js
app/views/_includes/components/option-select/index.html
app/views/application/education/add-certification.html
app/views/application/experience-details/job-details.html
app/views/application/experience-details/summary-of-activity.html
app/views/application/expertise-type/assessment-expertise.html
app/views/application/expertise/assessment-expertise.html
app/views/application/expertise/select-occupation.html
app/views/application/expertise/select-sector.html
app/views/application/expertise/select-subject.html

Content updates missed in the last sweep have been added

copy updates missed in last review

---

app/views/application/experience-details/summary-of-activity.html
app/views/application/professional-achievements/add-achievements.html

Update character count to word count

---

app/routes.js
app/views/application/no-sector.html
app/views/layout.html
app/views/register-your-interest/about-you.html
app/views/register-your-interest/anything-else.html
app/views/register-your-interest/confirmation.html
app/views/register-your-interest/delete.html
app/views/register-your-interest/how-did-you-hear-about-us.html
app/views/register-your-interest/index.html
app/views/register-your-interest/no-sector.html
app/views/register-your-interest/review-sectors.html
app/views/register-your-interest/review.html
app/views/register-your-interest/select-levels-business.html
app/views/register-your-interest/select-levels-care-services.html
app/views/register-your-interest/select-pathways-business.html
app/views/register-your-interest/select-route.html
app/views/register-your-interest/where-did-you-hear-about-experts.html

This PR adds:
- Content update on conditional reveal checkbox
- Width fix for review screen
- New step to ask "Where did you hear about applying to become a subject expert for Ofqual?"

Content tweaks, width of review page fix and new screen added

---

app/views/_includes/summary-cards/self-declaration.html
app/views/application/review.html
app/views/application/self-declaration/bankrupt.html
app/views/application/self-declaration/breach.html
app/views/application/self-declaration/index.html
app/views/application/self-declaration/misconduct.html

This PR adds updated screens for the self declaration section.

Update self declaration with screens

---

app/views/application/self-declaration/index.html

This PR updates the self declaration flow.

Update self declaration screens

---

app/routes.js
app/views/_includes/summary-cards/conflict-of-interest.html
app/views/application/conflict-of-interest/add-conflict.html
app/views/application/conflict-of-interest/delete.html
app/views/application/conflict-of-interest/index.html
app/views/application/conflict-of-interest/review.html
app/views/application/conflict-of-interest/section-completed.html
app/views/application/index.html
app/views/application/review.html

This PR adds the conflict of interest section.

Conflicts of interest

---

app/views/_includes/summary-cards/verify.html
app/views/application/index.html
app/views/application/review.html
app/views/application/verify-your-identity/index.html
app/views/application/verify-your-identity/review.html
app/views/application/verify-your-identity/section-completed.html

This PR adds a **very mvp** version of Verify your identity section.

Verify your identity added

---

app/data/session-data-defaults.js
app/routes.js
app/views/_includes/summary-cards/references.html
app/views/application/index.html
app/views/application/references/add-reference.html
app/views/application/references/delete.html
app/views/application/references/index.html
app/views/application/references/review.html
app/views/application/references/section-completed.html
app/views/application/review.html

This PR adds the references section:

Add references section

---

app/views/application/index.html
app/views/application/review.html

This PR consolidates a few tasks in the task list under the heading "Identity and verification checks"

Reshuffle task list

---

app/assets/sass/application.scss
app/assets/sass/overrides/layout.scss
app/views/application/education/add-certification.html
app/views/application/education/index.html
app/views/application/index.html
app/views/application/review.html
app/views/home.html
app/views/index.html
app/views/layout.html

This PR:
Updates the homepage content and the Qualifications section

Copy updates 2

---

app/routes.js
app/views/_includes/summary-cards/qualifications.html
app/views/application/education/add-qualifcation.html
app/views/application/education/upload-available.html
app/views/application/education/upload-qualification.html

This PR adds an upload certification question to the qualifications section.

Upload a certificate section added

---

app/data/session-data-defaults.js
app/views/application/search/select-level.html
app/views/application/search/select-qualification.html

This PR updates some content that we noticed was a bit broken in the last user research session.

Content tweaks

---

app/data/session-data-defaults.js
app/routes.js
app/views/_includes/summary-cards/teaching-expertise.html
app/views/application/teaching-expertise/currently-in-role.html

This PR adds an "Are you currently working in a teaching, lecturing or training role?" question.

Add "Are you currently working in a teaching, lecturing or training role?" question

---

app/data/session-data-defaults.js
app/routes.js

This PR hides the "areas..." section and also some and some tidy up to kick start the PR

Hide "areas..." section

---

app/views/application/references/add-reference.html

This PR adds the (optional) to the telephone field

Update label on telephone input

---

app/views/application/search/select-level.html

Addition of 'I don't know my level' checkbox.

Addition of checkbox

---

app/views/_includes/summary-cards/qualifications.html
app/views/application/education/add-qualifcation.html
app/views/application/education/upload-available.html
app/views/application/education/upload-qualification.html
app/views/application/experience-details/index.html
app/views/application/experience-details/job-details.html
app/views/application/start.html
app/views/home.html

Changes to the content on these pages:

Content update

---

app/data/qualificationData.json
app/views/_includes/summary-cards/assessment-expertise.html
app/views/_includes/summary-cards/industry-expertise.html
app/views/_includes/summary-cards/teaching-expertise.html
app/views/application/assessment-expertise/add-details.html
app/views/application/assessment-expertise/assessment-expertise.html
app/views/application/conflict-of-interest/add-conflict.html
app/views/application/conflict-of-interest/index.html
app/views/application/industry-expertise/add-details.html
app/views/application/references/index.html
app/views/application/search/index.html
app/views/application/search/select-expertise-type.html
app/views/application/teaching-expertise/add-details.html
app/views/application/teaching-expertise/teaching-expertise.html

This PR includes a bunch of copy updates!

Copy updates 101122

---

app/views/application/search/index.html
app/views/home.html

Content updates

---

app/data/session-data-defaults.js
app/views/_includes/summary-cards/qualifications.html
app/views/_includes/summary-cards/verify.html

This PR:
- adds a bunch or realistic dummy data to the prototype
- make the verification upload a link

Add realistic dummy application content

---

README.md

Added some info to the readme about how we convert the subjects spreadsheet that Katie provides as an Excel doc into json so the autocomplete can consume it.

Added some guidance around data to the readme

---

app/views/_includes/shared/application-sections.html
app/views/application/assessment-expertise/review.html
app/views/application/conflict-of-interest/review.html
app/views/application/education/review.html
app/views/application/experience-details/review.html
app/views/application/industry-expertise/review.html
app/views/application/personal-details/review.html
app/views/application/professional-memberships/review.html
app/views/application/references/review.html
app/views/application/right-to-work/review.html
app/views/application/search/review.html
app/views/application/self-declaration/review.html
app/views/application/teaching-expertise/review.html
app/views/application/verify-your-identity/review.html

Updates to review content. I have inserted some of the screenshots

content update for review screens

---

app/views/_includes/summary-cards/subjects.html
app/views/application/assessment-expertise/add-details.html
app/views/application/search/add-details.html
app/views/application/search/sector-search.html
app/views/application/search/select-expertise-type.html
app/views/application/teaching-expertise/add-details.html

flow updated with placeholder text

Expertise flow

---

app/views/application/assessment-expertise/add-details.html
app/views/application/industry-expertise/add-details.html
app/views/application/search/add-details.html
app/views/application/search/select-expertise-type.html
app/views/application/search/select-level.html
app/views/application/search/select-qualification.html
app/views/application/teaching-expertise/add-details.html
app/views/home.html

Removing 'other' qual type and references of this in caption headings. Content updates.

---

app/views/application/assessment-expertise/assessment-expertise.html

I created a new assessment branch because I made a mistake with the old one. Please have a look.

Assessment checkboxes new

---

app/views/application/assessment-expertise/assessment--add-details-marking.html

Assessment textbox 1

---

app/views/application/assessment-expertise/assessment--add-details-moderating.html

Assessment textbox 2 - moderating text box

---

app/views/application/assessment-expertise/assessment--add-details-designing.html

Assessment textbox 3 - designing assessments

---

app/views/application/assessment-expertise/assessment--add-details-reviewing.html

Assessment textbox 4 - Reviewing

---

app/views/application/teaching-expertise/teaching--add-details-developing.html

Addition of teaching textbox 1 - developing

---

app/views/application/teaching-expertise/teaching--add-details-senior-role.html

Addition of teaching textbox 2 - senior role

---

app/views/application/teaching-expertise/teaching--add-details-training-staff.html

Addition of textbox 3 - training

---

app/routes.js
app/views/_includes/summary-cards/subjects.html
app/views/application/assessment-expertise/add-details-designing.html
app/views/application/assessment-expertise/add-details-marking.html
app/views/application/assessment-expertise/add-details-moderating.html
app/views/application/assessment-expertise/add-details-reviewing.html
app/views/application/search/subject-search.html
app/views/application/search/teaching-expertise.html
app/views/application/teaching-expertise/add-details-developing.html
app/views/application/teaching-expertise/add-details-senior-role.html
app/views/application/teaching-expertise/add-details-training-staff.html

- adding subject bullet list on add details screens 
- adding routes for add details screens 
- fixing routes for task list 
- fixing showing granular expertise types on subject review screen
- fix route if subject with no defined qual type is selected, so it goes to qual type screen

Evidence section

---

app/views/_includes/summary-cards/industry-expertise.html

changes to industry review screen

---

app/routes.js
app/views/_includes/summary-cards/assessment-expertise.html
app/views/_includes/summary-cards/teaching-expertise.html
app/views/application/teaching-expertise/add-details-developing.html
app/views/application/teaching-expertise/add-details-senior-role.html
app/views/application/teaching-expertise/add-details-training-staff.html

Assessment and teaching expertise review screens, with updated routes

Updated review screens

---

app/views/_includes/components/footer.html

footer content update

---

app/data/session-data-defaults.js
app/views/_includes/summary-cards/assessment-expertise.html
app/views/_includes/summary-cards/communication-analytical-judgement-skills.html
app/views/_includes/summary-cards/conflict-of-interest.html
app/views/_includes/summary-cards/experience.html
app/views/_includes/summary-cards/industry-expertise.html
app/views/_includes/summary-cards/memberships.html
app/views/_includes/summary-cards/personal-details.html
app/views/_includes/summary-cards/professional-achievements.html
app/views/_includes/summary-cards/qualifications.html
app/views/_includes/summary-cards/references.html
app/views/_includes/summary-cards/right-to-work.html
app/views/_includes/summary-cards/self-declaration.html
app/views/_includes/summary-cards/subjects.html
app/views/_includes/summary-cards/teaching-expertise.html
app/views/_includes/summary-cards/verify.html

Prevent screenreader reading 'change' and visually hidden as one word.

updates for screenreader 

---

app/views/application/industry-expertise/index.html

Industry content update

---

app/data/session-data-defaults.js
app/views/_includes/shared/application-sections.html
app/views/_includes/summary-cards/communication-analytical-judgement-skills.html
app/views/application/communication-analytical-judgement-skills/index.html
app/views/application/communication-analytical-judgement-skills/review.html
app/views/application/communication-analytical-judgement-skills/section-completed.html
app/views/application/index.html
app/views/home.html

Updates to review screen & 'provide' sentence

communication content update

---

app/views/application/teaching-expertise/add-details-teaching-lecturing.html

text amendment to teaching and lecturing

---

app/views/application/index.html

sidebar content update

---

app/views/_includes/summary-cards/qualifications.html
app/views/application/education/index.html

Qualifications content update

---

app/views/application/submit.html

The anchor tag needs to be updated. I'm waiting for Katie to confirm the address link for this.

Content update for submit page

---

app/assets/sass/application.scss
app/assets/sass/components/messages.scss
app/assets/sass/overrides/gov-uk-nav.scss
app/data/session-data-defaults.js
app/routes.js
app/views/account/messages/application-received.html
app/views/account/messages/further-evidence-required.html
app/views/account/messages/index.html
app/views/account/messages/message-sent.html
app/views/account/messages/name-change-proof.html
app/views/account/messages/reply.html
app/views/account/messages/send-message.html
app/views/index.html
app/views/layout.html

Shows how the flow and design works for viewing inbox, viewing messages, replying to message, viewing reply, sending a message and viewing message. Unread and read statuses. 
Needs work to get unread to change to read after viewing and to get realistic dates.

Initial design for messages

---

app/assets/sass/application.scss
app/assets/sass/components/cards.scss
app/data/session-data-defaults.js
app/routes.js
app/views/_includes/summary-cards/application-status.html
app/views/_includes/summary-cards/subjects.html
app/views/account/index.html
app/views/index.html
app/views/layout.html

updating status name and colours. 
adding card to Home to link to other content in account area. 
adding links between application status and the subject breakdown.

account home design

---

app/data/session-data-defaults.js
app/routes.js
app/views/_includes/summary-cards/application-status.html
app/views/_includes/summary-cards/subjects.html
app/views/account/index.html
app/views/index.html

Setting up routes and session data for different application statuses.
Adding extra subject to session data.

Application status views

---

app/assets/sass/components/cards.scss
app/assets/sass/overrides/layout.scss
app/assets/sass/overrides/summary-card.scss
app/data/session-data-defaults.js
app/routes.js
app/views/_includes/summary-cards/subject-status.html
app/views/account/index.html
app/views/account/your-details/application.html
app/views/account/your-details/conflict-of-interest.html
app/views/account/your-details/references.html
app/views/account/your-details/self-declaration.html
app/views/account/your-details/subjects.html
app/views/index.html

Also includes: 
- tidy up of account Home. To set correct links and fix hover styling. 
- set pageHeading on all account pages so it appears in browser

Application status

---

app/views/_includes/summary-cards/application-status.html
app/views/index.html

Also changed name of Approved on prototype home page.

adding feedback message to status box when fully rejected

---

app/views/_includes/summary-cards/application-status.html

- adding text saying x of x specialism approved, when not all are rejected or approved.

Accept reject text

---

app/routes.js
app/views/account/index.html
app/views/account/submitted.html
app/views/application/submit.html
app/views/layout.html

- shows account navigation 
- link to account home 
- pressing 'submit' button on application now loads the data in so the account area is populated.

Submitted page updates

---

app/routes.js
app/views/account/messages/index.html
app/views/account/messages/supplier-form.html
app/views/account/messages/working-with-ofqual.html

supplier-form and working-with-ofqual
Will create a new branch for adding to messages table

Adding message pages

---

app/views/layout.html

For testing purposes. Will need proper calculating in future

Chaaged message indicator to display "3"

---

app/data/session-data-defaults.js
app/views/layout.html

Now displays correct number of unread messages based on any order post approval messages are opened Also added unread message data to session data defaults

Fixing msg indicator, added session data

---

app/views/account/messages/application-outcome.html
app/views/account/messages/index.html

- Rejected status session no longer has SMF or working with ofqual messages 
- Fully approved application outcome message no longer shows partial approval line

Fix correct messages for different status'

---

app/views/_includes/summary-cards/application-status.html
app/views/account/messages/application-outcome.html

Changing the application-status summary card copy to match session data (1 partial approval, 1 rejection") Also changed application-outcome message content to match the same above.

Changing application status copy

---

app/views/_includes/summary-cards/application-status.html
app/views/_includes/summary-cards/subject-status.html
app/views/index.html

Change subject-status summary card labels
Change application-status summary card labels 
Change admin home page label

Change "Rejected" label text to "Unsuccessful"

---

app/views/_includes/summary-cards/application-status.html
app/views/account/Projects/index.html
app/views/account/messages/application-outcome.html
app/views/account/your-details/application.html
app/views/account/your-details/conflict-of-interest/index.html
app/views/account/your-details/index.html
app/views/account/your-details/references.html
app/views/account/your-details/self-declaration.html
app/views/account/your-details/subjects.html

Change links in application-outcome message
Change links in application-summary
Copy changes to change copy to "outcomes"
Change nav copy to "detailed outcomes" instead of subject...status 
remove some irrelevant copy from detailed page

Updating links to detailed outcomes page

---

app/views/_includes/summary-cards/application-status.html
app/views/account/messages/application-outcome.html
app/views/account/your-details/outcome-overview.html

Change to application status summary card (homepage) 
Change to application-outcome message
Change to outcome-overview page summary table

Adding reassurance content for approved subjects

---

app/assets/javascripts/application.js
app/assets/javascripts/service-header.js
app/assets/sass/application.scss
app/assets/sass/overrides/blank.scss
app/assets/sass/overrides/service-header.scss
app/views/_includes/scripts.html
app/views/layout.html
app/views/layout_original.html
package.json

Adding onelogin header 
Thanks to Joe for the hand getting page indicators working

One login header

---

app/views/_includes/components/select-additional-check.html
app/views/account/your-details/application/additional-select-expertise-type.html

Commented out nunjucks code for ease of reference
added html version with more components (tags and content for unsuccessful items)

Enhancing design of select expertise for additional

---

app/views/account/Projects/index.html

Forecasted dates on current projects
Actual dates on completed
Remove estimated days on completed, add invoice amount.

Small content changes to match commissioning fields
